backend:
  name: github
  repo: wooldrum/wooldrum.github.io
  branch: main
  base_url: https://wooldrum-decap-oauth.vercel.app
  auth_endpoint: api/auth

site_url: https://wooldrum.github.io
logo_url: https://wooldrum.github.io/assets/images/channels4_profile.jpg

media_folder: "assets/images"
public_folder: "/assets/images"

publish_mode: simple

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sortable_fields: ["date", "title"]
    view_groups:
      - label: "Year"
        field: "date"
        pattern: "YYYY"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Hero Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
